name: Auto Ping Render (KST 6:00~1:00)

on:
  schedule:
    # UTC 21~23시 (KST 6~8시)
    - cron: "*/10 21-23 * * *"
    # UTC 0~16시 (KST 9~01시)
    - cron: "*/10 0-16 * * *"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render App
        run: curl -s https://psytest-checker.onrender.com
