name: Check ads.txt

on:
  push:
    branches:
      - main

jobs:
  check-ads:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: List Files
        run: ls -l
